#ifndef CONFIG_H
#define CONFIG_H

#define MAX_HAMBURGUERS 12
#define MAX_INGREDIENTES 10
#define MAX_PEDIDOS 6
#define MAX_COLUNAS_ESTOQUE 3
#define ESPACAMENTO_COLUNAS 20
#define TEMPO_EXIBICAO_RECEITA_SEGUNDOS 3
#define CAIXA_LIMITE_SALDO_NEGATIVO -500.0f

#endif
